### ISSUE TITLE
Cannot install through enaml-native cli

### ISSUE THREAD

**Issue by K3nn3th2** [codelv/enaml-native-icons#3]
As stated, i cannot install this package via enaml-native cli.
Am i missing a channel i should add?
This is the error:

(/home/archm4n/Documents/projects/ReggaeLoader/venv) [archm4n@4rr0w ReggaeLoader]$ enaml-native install enaml-native-icons
[INFO]:   -> running  /opt/miniconda3/condabin/conda install -y enaml-native-icons
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - enaml-native-icons

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Exception in thread background thread for pid 4846:
Traceback (most recent call last):
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /opt/miniconda3/condabin/conda install -y enaml-native-icons

  STDOUT:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - enaml-native-icons

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noa... (271 more, please see e.stdout)

  STDERR:

Traceback (most recent call last):
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/bin/enaml-native", line 10, in <module>
    sys.exit(main())
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/enamlnativecli/main.py", line 1765, in main
    EnamlNativeCli().start()
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/enamlnativecli/main.py", line 1759, in start
    cmd.run(self.args)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/enamlnativecli/main.py", line 753, in run
    shprint(self.cli.conda, 'install', '-y', *args.args)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/enamlnativecli/main.py", line 169, in shprint
    for c in cmd(*args, **kwargs):
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/archm4n/Documents/projects/ReggaeLoader/venv/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /opt/miniconda3/condabin/conda install -y enaml-native-icons

  STDOUT:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - enaml-native-icons

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noa... (271 more, please see e.stdout)

  STDERR:

**Comment by frmdstryr** [comment]
either add the codelv channel when installing with `-c codelv` or add codelv to your channels with `conda config --add channels codelv`

You may need to also update the gradle versions once installed
